#!/usr/bin/env node
/// <reference types="node" />
// 构建 client.js：rolldown（Rust 系 bundler，与 dsh 自身 tsdown 同底层）把
// src/client-entry.ts 打包为 CJS（react 外部化），再包进
// window.__ModuleLoader__.load({ id, factory }) UMD 外壳（factory(require)
// 收到模块系统的 require，module/exports 由外壳提供）。id 取 package.json
// 的 name，与 dsh.client 模块表键一致。
// 运行：node build-client.mjs（或 pnpm build:client）。buildClient() 供测试导入。
// 顶部 node reference：oxlint 类型检查对 .mjs 不自动加载 @types/node，需显式
// 声明才能解析 node:fs/node:path/process/import.meta（避免整文件按 error 类型
// 误报 unsafe）。

import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { rolldown } from "rolldown";
import { canonicalizeRegionPaths } from "@jayyuen66/dsh-plugin-shared/lib/canonicalize-region-paths";

/**
 * 对象守卫（shared/lib/tool-events 同款防御）：typeof 收窄为 Record 而不经断言。
 * @param {unknown} value
 * @returns {value is Record<string, unknown>}
 */
function isRecord(value) {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

const root = import.meta.dirname;

/** @type {unknown} */
const pkgJson = JSON.parse(readFileSync(path.join(root, "package.json"), "utf8"));
const pkgNameRaw = isRecord(pkgJson) ? pkgJson.name : undefined;
const pkgName = typeof pkgNameRaw === "string" ? pkgNameRaw : "unknown";

/** 生成 client.js 的完整文本（含 ModuleLoader 外壳）。 */
export async function buildClient() {
  const bundle = await rolldown({
    input: path.join(root, "src", "client-entry.ts"),
    external: ["react"],
    platform: "browser",
    resolve: {
      extensions: [".ts", ".mjs", ".js", ".json"],
    },
  });
  const { output } = await bundle.generate({
    format: "cjs",
  });
  const chunk = output.find((item) => item.type === "chunk");
  if (chunk === undefined) {
    throw new Error("rolldown generate returned no chunk output");
  }
  // 见 shared/lib/canonicalize-region-paths.ts：`//#region` 行的路径由 rolldown 按 process.cwd()
  // 算出 ⇒ 同一份源码两种字节。折 canonical 必须落在返回值之前（test/client-freshness.ts 逐字节
  // 比内存构建与磁盘产物），不能只在 writeFileSync 那一侧做。
  const body = canonicalizeRegionPaths(chunk.code.trimEnd(), root);
  return [
    "// GENERATED by buildClient() in build-client.mjs — edit src/client-entry.ts, then run `node build-client.mjs`.",
    "window.__ModuleLoader__.load({",
    `  id: '${pkgName}',`,
    "  factory: (require) => {",
    "    var module = { exports: {} };",
    "    var exports = module.exports;",
    body,
    "    return module.exports;",
    "  },",
    "});",
    "",
  ].join("\n");
}

async function main() {
  const out = await buildClient();
  writeFileSync(path.join(root, "client.js"), out, "utf8");
  console.info("client.js written:", out.length, "chars");
}

if (process.argv[1] === import.meta.filename) {
  try {
    await main();
  } catch (error) {
    console.error(error);
    process.exit(1);
  }
}
